Expose shape fields
Nilirad/bevy_prototype_lyon pull request #272
Opened 2024-12-30 16:44 UTC by carrascomj

### Description

Making the `Shape` fields public allows for surgical modifications without requiring to rebuild the `Path` when only changes to the color or the options of some field are desired.

### Implementation

* Made all `Shape` attributes public.
* Added an example of changing the fill and stroke without rebuilding the path.

This works since `src/plugins.rs:mesh_shapes_system` is triggered by changes in the fields of a `Shape`.

2024-12-30 16:47 UTC, carrascomj commented
Probably the getter methods of `Shape` should now be removed (?).

2025-01-26 13:10 UTC, Nilirad requested changes
The idea is correct: paths are quite expensive to calculate. I left some corrections suggested. You can also remove the getter methods of `Shape` since the fields are now public. For the rest, it looks good.

2025-01-26 13:10 UTC, Nilirad commented on examples/dynamic_stroke_size.rs
> +        transform.rotate(Quat::from_rotation_z(200. / get_max_x(shape) * delta));
For floating point notation consistency.

```suggestion
        transform.rotate(Quat::from_rotation_z(200.0 / get_max_x(shape) * delta));
```

2025-01-26 13:10 UTC, Nilirad commented on examples/dynamic_stroke_size.rs
> +        Transform::default().with_translation(Vec3::new(0., 0., 2.)),
```suggestion
        Transform::default().with_translation(Vec3::new(0.0, 0.0, 2.0)),
```

2025-01-26 13:10 UTC, Nilirad commented on examples/dynamic_stroke_size.rs
> +        Transform::default().with_translation(Vec3::new(0., 0., 1.)),
```suggestion
        Transform::default().with_translation(Vec3::new(0.0, 0.0, 1.0)),
```

2025-01-26 13:38 UTC, carrascomj commented
Great! I think that should be it, then.

2025-01-26 13:42 UTC, Nilirad approved these changes

2025-01-26 13:42 UTC, merged